apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - image: mysql:{{ .Values.imageTag }}
        name: {{ .Release.Name }}
        env:
          # Use secret in real usage
        - name: {{ .Release.Name }}_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: {{ .Release.Name }}
        volumeMounts:
        - name: {{ .Release.Name }}-persistent-storage
          mountPath: /var/lib/{{ .Release.Name }}
      volumes:
      - name: {{ .Release.Name }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pv-claim
