---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 3306
    - nodePort: 33306
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: mysql
